# NumPy

numpy is python's package for doing math that is more advanced than +-*/

This includes special functions like cosine, exponential, sqrt, ...

On top of this we can use numpy to generate samples from many types of random variables

numpy also has a powerful data type to define vectors, matrices, and tensors

With these data types numpy also allows us to do linear algebra - matrix multiplication and matrix-vector solutions

In [1]:
# the first step of using numpy is to tell python to use it
import numpy as np

In [2]:
print(np.cos(np.pi))
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))

-1.0
1.1
5.2


In [3]:
# we can create numpy arrays by converting lists
# this is a vector
vec = np.array([1,2,3])
print(vec)
# we can create matrices by converting lists of lists
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])
print('')
print(mat)
print('')
print(mat.T)

[1 2 3]

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[[1 4 1]
 [2 5 8]
 [1 9 9]]


In [4]:
# there are lots of other ways to create numpy arrays
vec2 = np.arange(0,15)
print(vec2)
print('')
vec3 = np.arange(3,21,6)
print(vec3)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 3  9 15]


In [5]:

vec4 = np.linspace(0,5,10)
print(vec4)
print('')
print(vec4.reshape(5,2))
vec4_reshaped = vec4.reshape(5,2)
print(vec4_reshaped)
print(vec4)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [6]:
mat2 = np.zeros([5,3])
print(mat2)
mat3 = np.ones((3,5))
print('')
print(mat3)
mat4 = np.eye(5)
print('')
print(mat4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [7]:
# we can +-*/ arrays together if they're the right size
vec5 = np.arange(1,6)
vec6 = np.arange(3,8)
print(vec5)
print(vec6)
print(vec5+vec6)
print(vec5*vec6)
print(1/vec5)
print(np.sqrt(vec6))

[1 2 3 4 5]
[3 4 5 6 7]
[ 4  6  8 10 12]
[ 3  8 15 24 35]
[1.         0.5        0.33333333 0.25       0.2       ]
[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [8]:
# we can do matrix multiplication
print(mat)
print('')
print(vec)
print()
product = np.matmul(mat,vec)
print(product)

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[1 2 3]

[ 8 41 44]


In [9]:
print(np.linalg.solve(mat,product))
print('')
print(np.linalg.inv(mat))

[1. 2. 3.]

[[ 0.5         0.18518519 -0.24074074]
 [ 0.5        -0.14814815  0.09259259]
 [-0.5         0.11111111  0.05555556]]


In [10]:
# we can find the unique values in an array
vec7 = np.array(['blue','red','orange','purple','purple','orange','Red',6])
print(vec7)
print(np.unique(vec7))

['blue' 'red' 'orange' 'purple' 'purple' 'orange' 'Red' '6']
['6' 'Red' 'blue' 'orange' 'purple' 'red']


In [11]:
# we can also use numpy to generate samples of a random variable
rand_mat = np.random.rand(5,5) # uniform random variable
print(rand_mat)
rand_mat2 = np.random.randn(10,5) # standard normal random variable
print('')
print(rand_mat2)

[[0.51455636 0.0418407  0.9127962  0.7811876  0.81735072]
 [0.90120642 0.81202447 0.31456234 0.9126753  0.88091418]
 [0.58038939 0.2970829  0.43474181 0.72725366 0.13037094]
 [0.72396114 0.95185801 0.31205929 0.89711173 0.74826376]
 [0.28121454 0.45068226 0.02243526 0.90771185 0.69443879]]

[[-3.88537268  0.70036773  0.60360298  0.13723625 -0.55145658]
 [ 1.50903367  1.12532807  0.30062262 -0.8198288  -0.47083279]
 [ 0.96778823 -0.29033872 -0.30332543 -1.5023813  -0.90507018]
 [ 1.22739274  0.10790077  1.90439782 -0.36304414 -0.11295997]
 [ 0.05591424  0.270761   -0.53661547  0.8143339   1.39837523]
 [ 0.29412153 -0.13241408  1.06111553  0.50373841 -0.90792563]
 [-1.11863583 -0.74034536  0.28478844  0.32427389 -0.66469516]
 [ 0.82970274 -1.7967009   1.05001483  1.83462096 -0.27782578]
 [ 1.27655482  1.84936345 -0.30648471  0.305631   -2.07270884]
 [ 0.85026022 -0.93755748 -0.24309186  1.76511775  0.47737397]]


In [12]:
# we can also use numpy for statistical tools on arrays
print(np.mean(rand_mat))
print(np.std(rand_mat2))

0.6019475843175678
1.100186316488651


In [13]:
print(np.min(rand_mat))
print(np.max(rand_mat2))

0.02243526135677676
1.9043978208786965


In [14]:
# break here for next video!

In [15]:
# how do we access entries in a numpy vector
rand_vec = np.random.randn(19)
print(rand_vec)
print(rand_vec[6])

[-0.37707893  0.56637936 -1.48043257 -0.03146153  1.51777653 -0.30397863
  0.62283713  1.24888757 -0.46961672 -0.99218608  0.73236815  0.25937651
  1.08497717 -2.32350112 -0.83726779  0.07762162 -0.2657503  -0.52275296
 -1.24229535]
0.62283713462221


In [16]:
# we can access multiple entries at once using :
print(rand_vec[4:9])

[ 1.51777653 -0.30397863  0.62283713  1.24888757 -0.46961672]


In [17]:
# we can also access multiple non-consecutive entries using np.arange
print(np.arange(0,15,3))
print(rand_vec[np.arange(0,15,3)])

[ 0  3  6  9 12]
[-0.37707893 -0.03146153  0.62283713 -0.99218608  1.08497717]


In [18]:
# what about matrices
print(rand_mat)
print(rand_mat[1][2])
print(rand_mat[1,2])


[[0.51455636 0.0418407  0.9127962  0.7811876  0.81735072]
 [0.90120642 0.81202447 0.31456234 0.9126753  0.88091418]
 [0.58038939 0.2970829  0.43474181 0.72725366 0.13037094]
 [0.72396114 0.95185801 0.31205929 0.89711173 0.74826376]
 [0.28121454 0.45068226 0.02243526 0.90771185 0.69443879]]
0.3145623446311385
0.3145623446311385


In [19]:
print(rand_mat[0:2,1:3])

[[0.0418407  0.9127962 ]
 [0.81202447 0.31456234]]


In [20]:
# let's change some values in an array!
print(rand_vec)
rand_vec[3:5] = 4
print('')
print(rand_vec)
rand_vec[3:5] = [1,2]
print('')
print(rand_vec)

[-0.37707893  0.56637936 -1.48043257 -0.03146153  1.51777653 -0.30397863
  0.62283713  1.24888757 -0.46961672 -0.99218608  0.73236815  0.25937651
  1.08497717 -2.32350112 -0.83726779  0.07762162 -0.2657503  -0.52275296
 -1.24229535]

[-0.37707893  0.56637936 -1.48043257  4.          4.         -0.30397863
  0.62283713  1.24888757 -0.46961672 -0.99218608  0.73236815  0.25937651
  1.08497717 -2.32350112 -0.83726779  0.07762162 -0.2657503  -0.52275296
 -1.24229535]

[-0.37707893  0.56637936 -1.48043257  1.          2.         -0.30397863
  0.62283713  1.24888757 -0.46961672 -0.99218608  0.73236815  0.25937651
  1.08497717 -2.32350112 -0.83726779  0.07762162 -0.2657503  -0.52275296
 -1.24229535]


In [21]:
print(rand_mat)
rand_mat[1:3,3:5] = 0
print('')
print(rand_mat)

[[0.51455636 0.0418407  0.9127962  0.7811876  0.81735072]
 [0.90120642 0.81202447 0.31456234 0.9126753  0.88091418]
 [0.58038939 0.2970829  0.43474181 0.72725366 0.13037094]
 [0.72396114 0.95185801 0.31205929 0.89711173 0.74826376]
 [0.28121454 0.45068226 0.02243526 0.90771185 0.69443879]]

[[0.51455636 0.0418407  0.9127962  0.7811876  0.81735072]
 [0.90120642 0.81202447 0.31456234 0.         0.        ]
 [0.58038939 0.2970829  0.43474181 0.         0.        ]
 [0.72396114 0.95185801 0.31205929 0.89711173 0.74826376]
 [0.28121454 0.45068226 0.02243526 0.90771185 0.69443879]]


In [22]:
sub_mat = rand_mat[0:2,0:3]
print(sub_mat)
sub_mat[:] = 3
print(sub_mat)


[[0.51455636 0.0418407  0.9127962 ]
 [0.90120642 0.81202447 0.31456234]]
[[3. 3. 3.]
 [3. 3. 3.]]


In [23]:
print(rand_mat)

[[3.         3.         3.         0.7811876  0.81735072]
 [3.         3.         3.         0.         0.        ]
 [0.58038939 0.2970829  0.43474181 0.         0.        ]
 [0.72396114 0.95185801 0.31205929 0.89711173 0.74826376]
 [0.28121454 0.45068226 0.02243526 0.90771185 0.69443879]]


In [24]:
sub_mat2 = rand_mat[0:2,0:3].copy()
sub_mat2[:] = 99
print(sub_mat2)
print(rand_mat)


[[99. 99. 99.]
 [99. 99. 99.]]
[[3.         3.         3.         0.7811876  0.81735072]
 [3.         3.         3.         0.         0.        ]
 [0.58038939 0.2970829  0.43474181 0.         0.        ]
 [0.72396114 0.95185801 0.31205929 0.89711173 0.74826376]
 [0.28121454 0.45068226 0.02243526 0.90771185 0.69443879]]


In [25]:
# break here for next video

In [26]:
# we can also access entries with logicals
rand_vec = np.random.randn(15)

print(rand_vec)
print(rand_vec>0)
print(rand_vec[rand_vec>0])

[ 1.23656164  1.13424213 -1.61415935  0.9531814  -1.18867888  1.40481344
  0.20879901 -2.31326949  1.66997661  1.1290655   0.96364775 -0.48360822
 -0.15140824 -0.02053712  0.04784239]
[ True  True False  True False  True  True False  True  True  True False
 False False  True]
[1.23656164 1.13424213 0.9531814  1.40481344 0.20879901 1.66997661
 1.1290655  0.96364775 0.04784239]


In [27]:
print(rand_mat2)
print(rand_mat2[rand_mat2>0])

[[-3.88537268  0.70036773  0.60360298  0.13723625 -0.55145658]
 [ 1.50903367  1.12532807  0.30062262 -0.8198288  -0.47083279]
 [ 0.96778823 -0.29033872 -0.30332543 -1.5023813  -0.90507018]
 [ 1.22739274  0.10790077  1.90439782 -0.36304414 -0.11295997]
 [ 0.05591424  0.270761   -0.53661547  0.8143339   1.39837523]
 [ 0.29412153 -0.13241408  1.06111553  0.50373841 -0.90792563]
 [-1.11863583 -0.74034536  0.28478844  0.32427389 -0.66469516]
 [ 0.82970274 -1.7967009   1.05001483  1.83462096 -0.27782578]
 [ 1.27655482  1.84936345 -0.30648471  0.305631   -2.07270884]
 [ 0.85026022 -0.93755748 -0.24309186  1.76511775  0.47737397]]
[0.70036773 0.60360298 0.13723625 1.50903367 1.12532807 0.30062262
 0.96778823 1.22739274 0.10790077 1.90439782 0.05591424 0.270761
 0.8143339  1.39837523 0.29412153 1.06111553 0.50373841 0.28478844
 0.32427389 0.82970274 1.05001483 1.83462096 1.27655482 1.84936345
 0.305631   0.85026022 1.76511775 0.47737397]


In [28]:

print(rand_vec)
print('')
rand_vec[rand_vec>0.5] = -5
print(rand_vec)

[ 1.23656164  1.13424213 -1.61415935  0.9531814  -1.18867888  1.40481344
  0.20879901 -2.31326949  1.66997661  1.1290655   0.96364775 -0.48360822
 -0.15140824 -0.02053712  0.04784239]

[-5.         -5.         -1.61415935 -5.         -1.18867888 -5.
  0.20879901 -2.31326949 -5.         -5.         -5.         -0.48360822
 -0.15140824 -0.02053712  0.04784239]


In [29]:
# let's save some arrays on the disk for use later!
np.save('saved_file_name',rand_mat2)


In [30]:
np.savez('zipped_file_name',rand_mat=rand_mat,rand_mat2=rand_mat2)

In [31]:
# now let's load it
loaded_vec = np.load('saved_file_name.npy')
loaded_zip = np.load('zipped_file_name.npz')

print(loaded_vec)
print('')
print(loaded_zip)

[[-3.88537268  0.70036773  0.60360298  0.13723625 -0.55145658]
 [ 1.50903367  1.12532807  0.30062262 -0.8198288  -0.47083279]
 [ 0.96778823 -0.29033872 -0.30332543 -1.5023813  -0.90507018]
 [ 1.22739274  0.10790077  1.90439782 -0.36304414 -0.11295997]
 [ 0.05591424  0.270761   -0.53661547  0.8143339   1.39837523]
 [ 0.29412153 -0.13241408  1.06111553  0.50373841 -0.90792563]
 [-1.11863583 -0.74034536  0.28478844  0.32427389 -0.66469516]
 [ 0.82970274 -1.7967009   1.05001483  1.83462096 -0.27782578]
 [ 1.27655482  1.84936345 -0.30648471  0.305631   -2.07270884]
 [ 0.85026022 -0.93755748 -0.24309186  1.76511775  0.47737397]]



In [32]:
print(loaded_zip['rand_mat'])
print('')
print(loaded_zip['rand_mat2'])

new_array  = loaded_zip['rand_mat']
print(new_array)

[[3.         3.         3.         0.7811876  0.81735072]
 [3.         3.         3.         0.         0.        ]
 [0.58038939 0.2970829  0.43474181 0.         0.        ]
 [0.72396114 0.95185801 0.31205929 0.89711173 0.74826376]
 [0.28121454 0.45068226 0.02243526 0.90771185 0.69443879]]

[[-3.88537268  0.70036773  0.60360298  0.13723625 -0.55145658]
 [ 1.50903367  1.12532807  0.30062262 -0.8198288  -0.47083279]
 [ 0.96778823 -0.29033872 -0.30332543 -1.5023813  -0.90507018]
 [ 1.22739274  0.10790077  1.90439782 -0.36304414 -0.11295997]
 [ 0.05591424  0.270761   -0.53661547  0.8143339   1.39837523]
 [ 0.29412153 -0.13241408  1.06111553  0.50373841 -0.90792563]
 [-1.11863583 -0.74034536  0.28478844  0.32427389 -0.66469516]
 [ 0.82970274 -1.7967009   1.05001483  1.83462096 -0.27782578]
 [ 1.27655482  1.84936345 -0.30648471  0.305631   -2.07270884]
 [ 0.85026022 -0.93755748 -0.24309186  1.76511775  0.47737397]]
[[3.         3.         3.         0.7811876  0.81735072]
 [3.         3.    

In [33]:
# we can also save/load as text files...but only single variables
np.savetxt('text_file_name.txt',rand_mat,delimiter=',')
rand_mat_txt = np.loadtxt('text_file_name.txt',delimiter=',')
print(rand_mat)
print('')
print(rand_mat_txt)

[[3.         3.         3.         0.7811876  0.81735072]
 [3.         3.         3.         0.         0.        ]
 [0.58038939 0.2970829  0.43474181 0.         0.        ]
 [0.72396114 0.95185801 0.31205929 0.89711173 0.74826376]
 [0.28121454 0.45068226 0.02243526 0.90771185 0.69443879]]

[[3.         3.         3.         0.7811876  0.81735072]
 [3.         3.         3.         0.         0.        ]
 [0.58038939 0.2970829  0.43474181 0.         0.        ]
 [0.72396114 0.95185801 0.31205929 0.89711173 0.74826376]
 [0.28121454 0.45068226 0.02243526 0.90771185 0.69443879]]
